spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/products
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

    ## JPA configurations
  jpa:
    hibernate:
      ## ddl: Data Definition Language en automatique
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8888


  ##server.servlet.context-path = /api
  ##spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl